######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 13 22:50:31 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h Song.h to_be_defined.h Trie.h
SOURCES += gui.cpp main.cpp Song.cpp Trie.cpp
