######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 5 17:23:15 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h playlist_item.h to_be_defined.h
SOURCES += gui.cpp main.cpp playlist_item.cpp
