######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 19 22:52:11 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.h PlaylistList.h Song.h to_be_defined.h Trie.h
SOURCES += gui.cpp main.cpp PlaylistList.cpp Song.cpp Trie.cpp
